{% set name = "xpra" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Xpra-org/xpra/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ba4d525344f94b09e7425c6770d5504f755a9b48ac555942bd51c009f1d12990

build:
  skip: true  # [not linux]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - xorg-libx11
    - xorg-libxrandr
    - xorg-libxtst
    - xorg-libxdamage
    - xorg-libxcomposite
    - xorg-libxres
    - xorg-libxcursor
    - xorg-libxinerama
    - xorg-xineramaproto
    - xorg-libxscrnsaver
    - xorg-libxi
    - xorg-libxfixes
    - xorg-libxext
    - libxkbfile
    - cython
    - glib
    - gtk3
    - pycairo
    - pygobject
    - pyopengl
    - pycups  # [linux]
    - pyyaml
    - lz4
    - cryptography
    - zeroconf
    - netifaces
    - dbus-python
    - openssl
    - paramiko
    - sshpass
    - brotli
    - python-gssapi
    - pykerberos
    - python-ldap
    - pyu2f
    - ffmpeg
    - x264
    - x265
    - libvpx
    - libwebp
    - libpng
    - libjpeg-turbo
    - pillow
    - gstreamer
    - libogg
    - lame
    - pandoc
    - rencode
  run:
    - python
    - libcxx
    - xorg-libx11
    - xorg-libxrandr
    - xorg-libxtst
    - xorg-libxdamage
    - xorg-libxcomposite
    - xorg-libxres
    - xorg-xineramaproto
    - xorg-libxi
    - xorg-libxfixes
    - xorg-libxext
    - libxkbfile
    - gtk3
    - pygobject
    - paramiko
    - dbus-python
    - zeroconf
    - pillow
    - cairo
    - sshpass
    - ffmpeg
    - x264
    - x265
    - libvpx
    - libjpeg-turbo
    - rencode

test:
  imports:
    - xpra
  requires:
    - pip
  commands:
    - pip check
    - test -e $PREFIX/bin/xpra

about:
  home: https://github.com/Xpra-org/xpra
  summary: 'xpra: "screen for X"'
  description: |
    Xpra is known as "screen for X" : its seamless mode allows you to run X11 programs, usually on a
    remote host, direct their display to your local machine, and then to disconnect from these programs
    and reconnect from the same or another machine(s), without losing any state. Effectively giving you
    remote access to individual graphical applications.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://github.com/Xpra-org/xpra/wiki
  dev_url: https://github.com/Xpra-org/xpra

extra:
  recipe-maintainers:
    - erykoff
